Go 
CREATE DATABASE PROYECTO2
GO 
USE PROYECTO2


CREATE FUNCTION EXISTE (@ID VARCHAR(13)) RETURNS INT 
AS
BEGIN
	DECLARE @NOMBRE VARCHAR(100)
	SET @NOMBRE = (SELECT NOMBRE1 FROM PERSONA WHERE CUI = @ID)
	DECLARE @RETORNO INT
	SET @RETORNO = 1
	IF(@NOMBRE <> NULL)
		BEGIN
			SET @RETORNO = 1
		END
	ELSE
		BEGIN
			SET @RETORNO = 0
		END
	RETURN @RETORNO
END
--CREACION DE TABLAS
CREATE TABLE CONTINENTE 
(
	NOMBRE_CONTINENTE VARCHAR(10) PRIMARY KEY
)

CREATE TABLE PAIS
(
	NOMBRE_PAIS VARCHAR(50) PRIMARY KEY,
	NOMBRE_CONTINENTE VARCHAR(10) NOT NULL
)
ALTER TABLE PAIS ADD CONSTRAINT FK_PAIS FOREIGN KEY (NOMBRE_CONTINENTE) REFERENCES CONTINENTE(NOMBRE_CONTINENTE)

CREATE TABLE CIUDAD
(
	NOMBRE_CIUDAD VARCHAR(50) NOT NULL,
	NOMBRE_PAIS VARCHAR(50) NOT NULL
)
ALTER TABLE CIUDAD ADD CONSTRAINT FK_CIUDAD FOREIGN KEY (NOMBRE_PAIS) REFERENCES PAIS(NOMBRE_PAIS)
ALTER TABLE CIUDAD ADD CONSTRAINT PK_CIUDAD PRIMARY KEY (NOMBRE_CIUDAD, NOMBRE_PAIS)

CREATE TABLE DEPARTAMENTO
(
	NOMBRE_DEPTO VARCHAR(50) PRIMARY KEY
)

CREATE TABLE MUNICIPIO
(
	NOMBRE_MUNICIPIO VARCHAR(50) PRIMARY KEY,
	NOMBRE_DEPTO VARCHAR(50) NOT NULL
)
ALTER TABLE MUNICIPIO ADD CONSTRAINT FK_MUNICIPIO FOREIGN KEY (NOMBRE_DEPTO) REFERENCES DEPARTAMENTO(NOMBRE_DEPTO)

CREATE TABLE ZONA
(
	NUMERO_ZONA INT NOT NULL,
	NOMBRE_MUNICIPIO VARCHAR(50) NOT NULL
)
ALTER TABLE ZONA ADD CONSTRAINT FK_ZONA FOREIGN KEY (NOMBRE_MUNICIPIO) REFERENCES MUNICIPIO(NOMBRE_MUNICIPIO)
ALTER TABLE ZONA ADD CONSTRAINT PK_ZONA PRIMARY KEY (NUMERO_ZONA, NOMBRE_MUNICIPIO)

CREATE TABLE PERSONA
(
	CUI VARCHAR(13) PRIMARY KEY,
	NUMERO_ZONA INT NOT NULL,
	NOMBRE_MUNICIPIO VARCHAR(50) NOT NULL,
	NOMBRE1 VARCHAR(50) NOT NULL,
	NOMBRE2 VARCHAR(50),
	NOMBRE3 VARCHAR(50),
	APELLIDO1 VARCHAR(50) NOT NULL,
	APELLIDO2 VARCHAR(50),
	PADRE VARCHAR(13),
	MADRE VARCHAR(13),
	FECHA_NACIMIENTO DATE NOT NULL,
	GENERO VARCHAR(1) NOT NULL,
	PASAPORTE VARCHAR(9) UNIQUE
)
ALTER TABLE PERSONA ADD CONSTRAINT FK_ZONA_P FOREIGN KEY (NUMERO_ZONA, NOMBRE_MUNICIPIO) REFERENCES ZONA(NUMERO_ZONA, NOMBRE_MUNICIPIO)
ALTER TABLE PERSONA ADD CONSTRAINT UC_CUI CHECK (LEN(CUI) = 13)
ALTER TABLE PERSONA ADD CONSTRAINT UC_PASAPORTE CHECK (LEN(PASAPORTE) = 9)
ALTER TABLE PERSONA ADD CONSTRAINT UC_PADRE CHECK (dbo.EXISTE(PADRE) = 1 OR PADRE = NULL)
ALTER TABLE PERSONA ADD CONSTRAINT UC_MADRE CHECK (dbo.EXISTE(MADRE) = 1 OR MADRE = NULL)
ALTER TABLE PERSONA ADD CONSTRAINT UC_GENERO CHECK (GENERO = 'F' OR GENERO = 'M')

CREATE TABLE VIAJE
(
	ID_VIAJE INT PRIMARY KEY,
	PASAPORTE VARCHAR(9) NOT NULL,
	NOMBRE_CIUDAD VARCHAR(50) NOT NULL,
	NOMBRE_PAIS VARCHAR(50) NOT NULL,
	MOTIVO VARCHAR(100) NOT NULL,
	FECHA DATE NOT NULL
)
ALTER TABLE VIAJE ADD CONSTRAINT FK_PASAPORTE FOREIGN KEY (PASAPORTE) REFERENCES PERSONA(PASAPORTE)
ALTER TABLE VIAJE ADD CONSTRAINT FK_NOMBRE_C_P FOREIGN KEY (NOMBRE_CIUDAD, NOMBRE_PAIS) REFERENCES CIUDAD(NOMBRE_CIUDAD, NOMBRE_PAIS)

CREATE TABLE ESCANER
(
	ID_ESCANER INT PRIMARY KEY,
	NUMERO_ZONA INT NOT NULL,
	NOMBRE_MUNICIPIO VARCHAR(50) NOT NULL
)
ALTER TABLE ESCANER ADD CONSTRAINT FK_Z_M FOREIGN KEY (NUMERO_ZONA, NOMBRE_MUNICIPIO) REFERENCES ZONA (NUMERO_ZONA, NOMBRE_MUNICIPIO)

CREATE TABLE DIAGNOSTICO
(
	ID_DIAGNOSTICO INT PRIMARY KEY,
	CUI VARCHAR(13) NOT NULL,
	ID_ESCANER INT NOT NULL,
	FECHA DATE NOT NULL,
	TIEMPO INT NOT NULL,
	PORTADOR TINYINT NOT NULL,
	ASINTOMATICO TINYINT NOT NULL
)
ALTER TABLE DIAGNOSTICO ADD CONSTRAINT FK_CUI_D FOREIGN KEY (CUI) REFERENCES PERSONA(CUI)
ALTER TABLE DIAGNOSTICO ADD CONSTRAINT FK_ID_ESCANER FOREIGN KEY (ID_ESCANER) REFERENCES ESCANER(ID_ESCANER)
ALTER TABLE DIAGNOSTICO ADD CONSTRAINT UC_PORTADOR CHECK (PORTADOR = 1 OR PORTADOR = 0)
ALTER TABLE DIAGNOSTICO ADD CONSTRAINT UC_ASINTOMATICO CHECK ((ASINTOMATICO = 1 AND PORTADOR = 1) OR (ASINTOMATICO = 0 AND PORTADOR = 1) OR (ASINTOMATICO = 0 AND PORTADOR = 0))
ALTER TABLE DIAGNOSTICO ADD CONSTRAINT UC_TIEMPO CHECK ((TIEMPO >= 0 AND PORTADOR = 1) OR (TIEMPO = 0 AND PORTADOR = 0))

INSERT INTO DEPARTAMENTO VALUES ('GUATEMALA')
INSERT INTO DEPARTAMENTO VALUES ('PETEN')
INSERT INTO MUNICIPIO VALUES ('GUATEMALA', 'GUATEMALA')
INSERT INTO MUNICIPIO VALUES ('SAN BENITO', 'PETEN')
INSERT INTO MUNICIPIO VALUES ('VILLA CANALES', 'GUATEMALA')
INSERT INTO MUNICIPIO VALUES ('FLORES', 'PETEN')
INSERT INTO ZONA VALUES(1, 'GUATEMALA')
INSERT INTO ZONA VALUES(2, 'GUATEMALA')
INSERT INTO ZONA VALUES(3, 'SAN BENITO')
INSERT INTO ZONA VALUES(4, 'SAN BENITO')
INSERT INTO ZONA VALUES(5, 'VILLA CANALES')
INSERT INTO ZONA VALUES(6, 'VILLA CANALES')
INSERT INTO ZONA VALUES(7, 'FLORES')
INSERT INTO ZONA VALUES(8, 'FLORES')

INSERT INTO PERSONA VALUES('1234567891234', 1, 'GUATEMALA', 'SERGIO', 'DANIEL', 'JUAN', 'LARA', 'VASQUEZ', NULL, NULL, '12/12/1998', 'M','123456789')
INSERT INTO PERSONA VALUES('1234567891235', 2, 'GUATEMALA', 'ANDRES', 'JAVIER', 'MATIAS', 'GALVEZ', 'RIOS', NULL, NULL, '12/12/1998', 'M','123456780')
INSERT INTO PERSONA VALUES('1234567891236', 3, 'SAN BENITO', 'DANIELA', 'ESTRELLA', 'JOSE', 'ZAMORA', 'HIDELZ', NULL, NULL, '12/12/1999', 'F','123456781')
INSERT INTO PERSONA VALUES('1234567891237', 4, 'SAN BENITO', 'LAURA', 'MELISA', 'DINA', 'PAZ', 'PAZ', NULL, NULL, '12/12/1999', 'F','123456782')
INSERT INTO PERSONA VALUES('1234567891238', 5, 'VILLA CANALES', 'DIEGO', 'FERNANDO', 'JOSE', 'LARA', 'PAZ', '1234567891234', '1234567891237', '12/12/2005', 'M', NULL)
INSERT INTO PERSONA VALUES('1234567891239', 6, 'VILLA CANALES', 'LAURA', 'ANDREA', 'JOSEFA', 'GALVEZ', 'ZAMORA', '1234567895', '1234567891236', '12/12/2005', 'F','123456783')
INSERT INTO PERSONA VALUES('1234567891230', 7, 'FLORES', 'EDUARDO', 'ROBERTO', 'JOSE', 'ALBARIZAEZ', 'PAIZ', '1234567891238', '1234567891239', '12/12/2019', 'M', '123456784')
INSERT INTO PERSONA VALUES('1234567891231', 8, 'FLORES', 'EVELYN', 'LISBETH', 'JOSEFA', 'GALVEZ', 'ZAMORA', NULL, NULL, '12/12/2005', 'F','123456785')

INSERT INTO CONTINENTE VALUES ('AMERICA')
INSERT INTO CONTINENTE VALUES ('EUROPA')
INSERT INTO PAIS VALUES ('MEXICO', 'AMERICA')
INSERT INTO PAIS VALUES ('PERU', 'AMERICA')
INSERT INTO PAIS VALUES ('ESPAÑA', 'EUROPA')
INSERT INTO PAIS VALUES ('FRANCIA', 'EUROPA')
INSERT INTO CIUDAD VALUES ('MEXICO CITY', 'MEXICO')
INSERT INTO CIUDAD VALUES ('CUZCO', 'PERU')
INSERT INTO CIUDAD VALUES ('MADRID', 'ESPAÑA')
INSERT INTO CIUDAD VALUES ('PARIS', 'FRANCIA')

INSERT INTO VIAJE VALUES (1, '123456789', 'MEXICO CITY', 'MEXICO', 'NEGOCIOS', '01/20/2020')
INSERT INTO VIAJE VALUES (2, '123456789', 'CUZCO', 'PERU', 'TURISMO', '02/20/2020')
INSERT INTO VIAJE VALUES (3, '123456781', 'CUZCO', 'PERU', 'TURISMO', '02/20/2020')
INSERT INTO VIAJE VALUES (4, '123456782', 'MADRID', 'ESPAÑA', 'TURISMO', '03/20/2020')
INSERT INTO VIAJE VALUES (5, '123456782', 'MEXICO CITY', 'MEXICO', 'TURISMO', '03/25/2020')
INSERT INTO VIAJE VALUES (6, '123456784', 'PARIS', 'FRANCIA', 'NEGOCIOS', '03/20/2020')
INSERT INTO VIAJE VALUES (7, '123456784', 'MADRID', 'ESPAÑA', 'NEGOCIOS', '03/30/2020')

INSERT INTO ESCANER VALUES (1, 1, 'GUATEMALA')
INSERT INTO ESCANER VALUES (2, 2, 'GUATEMALA')
INSERT INTO ESCANER VALUES (3, 3, 'SAN BENITO')
INSERT INTO ESCANER VALUES (4, 4, 'SAN BENITO')

INSERT INTO DIAGNOSTICO VALUES (1, '1234567891234', 1, '05/04/2020', 0, 0, 0)
INSERT INTO DIAGNOSTICO VALUES (2, '1234567891234', 1, '05/10/2020', 9, 1, 0)
INSERT INTO DIAGNOSTICO VALUES (3, '1234567891235', 2, '05/04/2020', 0, 0, 0)
INSERT INTO DIAGNOSTICO VALUES (4, '1234567891236', 3, '05/10/2020', 5, 1, 1)
INSERT INTO DIAGNOSTICO VALUES (5, '1234567891237', 4, '05/04/2020', 0, 1, 1)
INSERT INTO DIAGNOSTICO VALUES (6, '1234567891237', 1, '05/10/2020', 9, 1, 0)