CREATE OR ALTER PROCEDURE uspINGRESO @PATH VARCHAR(200) AS
BEGIN
	IF OBJECT_ID('VISTA') IS NOT NULL
		BEGIN
			PRINT 'VISTA CREADA'
		END
	ELSE
		BEGIN
			CREATE OR ALTER VIEW VISTA
			AS SELECT ALIAS, E_MAIL, PRIMERNOMBRE, PRIMERAPELLIDO, FECHADENACIMIENTO
			FROM USUARIO;
		END

	BULK INSERT VISTA
	FROM @PATH
	WITH
	(
		FIELDTERMINATOR = ',',
		ROWTERMINATOR = '\n'
	)
END