--INSERT INTO USUARIO (ALIAS, E_MAIL, PRIMERNOMBRE, PRIMERAPELLIDO, FECHADENACIMIENTO) VALUES ('FLZAM', 'F@GMAIL.COM', 'FLOR', 'ZAMORA', '11-11-1997')
--SELECT * FROM USUARIO

--TRUNCATE TABLE USUARIO

CREATE OR ALTER VIEW VISTA
AS SELECT ALIAS, E_MAIL, PRIMERNOMBRE, PRIMERAPELLIDO, FECHADENACIMIENTO
FROM USUARIO;

BULK INSERT VISTA
FROM 'C:\Users\srgio\Desktop\Datos2.txt'
WITH
(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n'
);

SELECT * FROM VISTA;
SELECT * FROM USUARIO

DROP VIEW VISTA;
