-- Cantidad de pruebas realizadas por departamento, municipio y zona según la
-- ubicación de los aparatos. (mostrando cantidad de casos positivos y negativos)
--por zona
SELECT COUNT(1) AS GRUPO FROM DIAGNOSTICO A
INNER JOIN ESCANER B ON A.ID_ESCANER = B.ID_ESCANER
INNER JOIN ZONA C ON B.NUMERO_ZONA = C.NUMERO_ZONA
GROUP BY A.Portador

--por municipio
SELECT COUNT(1) AS GRUPO FROM DIAGNOSTICO A
INNER JOIN ESCANER B ON A.ID_ESCANER = B.ID_ESCANER
INNER JOIN ZONA C ON B.NUMERO_ZONA = C.NUMERO_ZONA
INNER JOIN MUNICIPIO D on C.NOMBRE_MUNICIPIO = D.NOMBRE_MUNICIPIO
GROUP BY A.Portador

-- por departamento
SELECT COUNT(1) AS GRUPO FROM DIAGNOSTICO A
INNER JOIN ESCANER B ON A.ID_ESCANER = B.ID_ESCANER
INNER JOIN ZONA C ON B.NUMERO_ZONA = C.NUMERO_ZONA
INNER JOIN MUNICIPIO D on C.NOMBRE_MUNICIPIO = D.NOMBRE_MUNICIPIO
INNER JOIN DEPARTAMENTO E on D.NOMBRE_DEPTO = E.NOMBRE_DEPTO
GROUP BY A.Portador


-- Cuantas personas han pasado por 3 o más puntos de control el mismo día dentro
-- del mismo municipio y han dado positivo. 
SELECT COUNT(1) AS CANT_PERSONAS
FROM DIAGNOSTICO D INNER JOIN ESCANER E ON (D.ID_ESCANER = E.ID_ESCANER)
WHERE PORTADOR = 1
GROUP BY D.FECHA, E.NOMBRE_MUNICIPIO, D.CUI
HAVING COUNT(1) >= 3