--Listado de asistencias (marcajes) de todo el personal, para el mes actual, ordenado por
--fecha de asistencia y nombre departamento/facultad.
SELECT * FROM 
ASISTENCIA A INNER JOIN EMPLEADO E ON (A.ID_EMPLEADO = E.ID_EMPLEADO) 
INNER JOIN DOCENTE D ON (E.ID_EMPLEADO = D.ID_EMPLEADO)
WHERE DATEPART(YEAR, FECHA) = 2020 AND DATEPART(MONTH, FECHA) = 5
ORDER BY A.FECHA, D.FACULTAD

--Cantidad de llegadas tarde del personal administrativo, por cada departamento de los
--últimos 15 días. (no tomar en cuenta inasistencias)
SELECT AD.DEPARTAMENTO, COUNT(1) AS CANTIDAD FROM
ADMINISTRATIVO AD INNER JOIN EMPLEADO E ON (E.ID_EMPLEADO = AD.ID_EMPLEADO) INNER JOIN ASISTENCIA A ON (E.ID_EMPLEADO = A.ID_EMPLEADO)
WHERE (A.HORA > E.HORA_ENTRADA) AND (DATEDIFF(DAY, A.FECHA, GETDATE()) <= 15)
GROUP BY AD.DEPARTAMENTO

--Listado de personas que no se presentaron el día de hoy. Ordenado por apellido y edad.
SELECT E.NOMBRE, E.APELLIDO, DATEDIFF(YEAR, E.FECHA_NACIMIENTO, GETDATE()) AS EDAD
FROM EMPLEADO E
WHERE E.ID_EMPLEADO NOT IN (SELECT E.ID_EMPLEADO FROM
	EMPLEADO E INNER JOIN ASISTENCIA A ON (E.ID_EMPLEADO = A.ID_EMPLEADO) WHERE A.FECHA = GETDATE())
ORDER BY APELLIDO, FECHA_NACIMIENTO

-- Cantidad de personas por turno y por género. 
SELECT COUNT(1) AS CANTIDAD, E.GENERO, E.HORA_ENTRADA 
FROM EMPLEADO E
GROUP BY E.GENERO, E.HORA_ENTRADA

-- Listado de personas que tienen ambos roles, administrativo y docente.
SELECT E.NOMBRE, E.APELLIDO, E.ID_EMPLEADO 
FROM EMPLEADO E INNER JOIN ADMINISTRATIVO A ON (E.ID_EMPLEADO = A.ID_EMPLEADO) 
	INNER JOIN DOCENTE D ON (A.ID_EMPLEADO = D.ID_EMPLEADO)

--Cantidad de inasistencias por departamento para el mes actual (días laborales).
SELECT AD.DEPARTAMENTO, (COUNT(1)) FROM
EMPLEADO E INNER JOIN ASISTENCIA A ON (E.ID_EMPLEADO = A.ID_EMPLEADO) INNER JOIN ADMINISTRATIVO AD ON (E.ID_EMPLEADO = AD.ID_EMPLEADO)
WHERE (DATEPART(MONTH, A.FECHA) = DATEPART(MONTH, GETDATE())) AND (DATEPART(YEAR, A.FECHA) = DATEPART(YEAR, GETDATE()))
GROUP BY AD.DEPARTAMENTO

--Listado del personal administrativo con su respectivo jefe inmediato. 
SELECT E.NOMBRE AS JEFE, E2.NOMBRE AS EMPLEADO, A.ID_EMPLEADO
FROM ADMINISTRATIVO A INNER JOIN EMPLEADO E ON A.JEFE = E.ID_EMPLEADO INNER JOIN EMPLEADO E2 ON (A.ID_EMPLEADO = E2.ID_EMPLEADO)
ORDER BY JEFE
